# Generated by Django 2.1 on 2019-03-08 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(verbose_name='데이터')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일자')),
            ],
        ),
    ]
