# Generated by Django 2.1 on 2019-03-28 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0002_wifidatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleMeshDataMdodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255, verbose_name='event name')),
                ('device_name', models.CharField(max_length=255, verbose_name='device name')),
                ('data_co', models.IntegerField(verbose_name='Co 가스 데이터')),
                ('data_h2s', models.IntegerField(verbose_name='H2S 가스 데이터')),
                ('data_o2', models.IntegerField(verbose_name='O2 가스 데이터')),
                ('data_ch4', models.IntegerField(verbose_name='CH4 가스 데이터')),
                ('doc_name', models.CharField(max_length=128, verbose_name='도크명')),
                ('ship_name', models.CharField(max_length=128, verbose_name='선박명')),
                ('set_no', models.CharField(max_length=128, verbose_name='세트순번')),
                ('location', models.CharField(max_length=128, verbose_name='설치위치')),
                ('node_no', models.CharField(max_length=128, verbose_name='노드순번')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일자')),
                ('coreid', models.CharField(max_length=128, verbose_name='coreid')),
            ],
            options={
                'db_table': 'multiple_mesh_data',
            },
        ),
    ]
