# Generated by Django 2.1 on 2019-03-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0003_multiplemeshdatamdodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplemeshdatamdodel',
            name='node_role',
            field=models.CharField(default='sr', max_length=128, verbose_name='노드역할'),
            preserve_default=False,
        ),
    ]
