# Generated by Django 2.1 on 2019-03-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0004_multiplemeshdatamdodel_node_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplemeshdatamdodel',
            name='volt',
            field=models.FloatField(default=0.0, verbose_name='Voltage'),
        ),
    ]
