# Generated by Django 2.1 on 2019-09-16 07:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0005_multiplemeshdatamdodel_volt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudMeshDataMdodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255, verbose_name='event name')),
                ('device_name', models.CharField(max_length=255, verbose_name='device name')),
                ('data_co', models.IntegerField(verbose_name='Co 가스 데이터')),
                ('data_o2', models.FloatField(verbose_name='O2 가스 데이터')),
                ('data_ch4', models.IntegerField(verbose_name='CH4 가스 데이터')),
                ('data_temp', models.FloatField(verbose_name='온도 데이터')),
                ('data_humid', models.IntegerField(verbose_name='습도 데이터')),
                ('volt', models.FloatField(default=0.0, verbose_name='Voltage')),
                ('doc_name', models.CharField(max_length=128, verbose_name='도크명')),
                ('ship_name', models.CharField(max_length=128, verbose_name='선박명')),
                ('set_no', models.CharField(max_length=128, verbose_name='세트순번')),
                ('node_role', models.CharField(max_length=128, verbose_name='노드역할')),
                ('location', models.CharField(max_length=128, verbose_name='설치위치')),
                ('node_no', models.CharField(max_length=128, verbose_name='노드순번')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('coreid', models.CharField(max_length=128, verbose_name='coreid')),
            ],
            options={
                'db_table': 'cloud_mesh_data',
            },
        ),
    ]
