# Generated by Django 2.1 on 2019-11-22 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0006_cloudmeshdatamdodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatM1LocationMdodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255, verbose_name='device name')),
                ('latitude', models.IntegerField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
            ],
            options={
                'db_table': 'device_location_data',
            },
        ),
        migrations.CreateModel(
            name='CatM1SensorDataMdodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255, verbose_name='device name')),
                ('data_co', models.IntegerField(verbose_name='Co 가스 데이터')),
                ('data_o2', models.FloatField(verbose_name='O2 가스 데이터')),
                ('data_ch4', models.IntegerField(verbose_name='CH4 가스 데이터')),
                ('data_temp', models.FloatField(verbose_name='온도 데이터')),
                ('data_humid', models.IntegerField(verbose_name='습도 데이터')),
                ('volt', models.FloatField(default=0.0, verbose_name='Voltage')),
                ('dock_name', models.CharField(max_length=128, verbose_name='도크명')),
                ('shipname', models.CharField(max_length=128, verbose_name='선박명')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
            ],
            options={
                'db_table': 'catm1_sensor_data',
            },
        ),
    ]
