# Generated by Django 2.1 on 2019-11-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0007_catm1locationmdodel_catm1sensordatamdodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catm1locationmdodel',
            name='latitude',
            field=models.FloatField(verbose_name='위도'),
        ),
    ]
